### ISSUE TITLE
Errors do not result in a non-zero exit code

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk.CommandLine#11]
Whenever an error occurs within the Augurk CommandLine a non-zero exit code should be returned to indicate that an error has occurred. Currently this is not the case, causing behaviour like augurk/vsts-extension#2, We should probably fix this, or fix this as a part of Augurk/Augurk#40

**Comment by simondel** [comment]
@jmezach Any update on this? This issue is closed but it's still an issue.

**Comment by jmezach** [comment]
@simondel Are you using the new cross-platform command line tool? It should be fixed there. What is the scenario in which you get this?

**Comment by simondel** [comment]
Turns out this was caused by the old 0.5.0 extension that we had for some reason. The new extension (with cli 4.0.0) does cause a red build 👍

**Comment by jmezach** [comment]
Yeah, the old version also uses the old CLI exclusively, so it wouldn't work there ;). Thanks for reporting back on this.
