### ISSUE TITLE
Azure devops publish task does not use additional options

### ISSUE THREAD

**Issue by rouke-broersma** [Augurk/Augurk.CommandLine#21]
We have authentication on our augurk instance, and set up the build task with Advanced/Additional Arguments: --useIntegratedSecurity but this does not seem to be passed to the augurk publish command, see logging:

```
\9\_work\_temp\8109c6c7-c233-4ebb-b662-16c564db26a3\augurk.exe publish --url https://augurk/ --productName product--groupName group--featureFiles **list-of-feature-files**
Starting publishing of feature files...
Publishing feature 'AddNewUserToCRM' version '0.0.0' to uri 'https://augurk/api/v2/products/product/groups/group/features/Feature/versions/0.0.0/' resulted in statuscode 'Unauthorized'
```

**Comment by jmezach** [comment]
This is probably an oversight in the conversion to TypeScript to make this cross-platform. Looks like we don't use the additional arguments anywhere. We should probably add that [here](https://github.com/Augurk/vsts-extension/blob/78155245b27fec74c56dfaa56a58f97ddb261c14/src/build-task/AugurkCLI/cli.ts#L33).
